name: Swaglabs with Maven and SafariDriver

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # Use macOS as the runner since SafariDriver is only available on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' # Use JDK 17 for your project
        distribution: 'temurin'
        cache: maven

    - name: Install SafariDriver
      run: |
        # Enable Safari's WebDriver
        sudo safaridriver --enable
        safaridriver --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests with Safari
      run: mvn -B test -Dsurefire.safari.driver=true

    # Optional: Upload dependency graph for Dependabot
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
