name: Swaglabs with Maven and SafariDriver

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # Use macOS for SafariDriver
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Enable SafariDriver
      run: |
        sudo safaridriver --enable
        safaridriver --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests with Safari
      run: mvn clean verify -Dbrowsername=safari
